/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface RadialCrispr {}
  interface RadialCrisprAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'RadialCrispr': Components.RadialCrispr;
  }

  interface StencilIntrinsicElements {
    'radial-crispr': Components.RadialCrisprAttributes;
  }


  interface HTMLRadialCrisprElement extends Components.RadialCrispr, HTMLStencilElement {}
  var HTMLRadialCrisprElement: {
    prototype: HTMLRadialCrisprElement;
    new (): HTMLRadialCrisprElement;
  };

  interface HTMLElementTagNameMap {
    'radial-crispr': HTMLRadialCrisprElement
  }

  interface ElementTagNameMap {
    'radial-crispr': HTMLRadialCrisprElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
